from __future__ import annotations
from pathlib import Path
import re

ADAPTER_NAME = "superpowers"
ADAPTER_RULE_VERSION = "v1"
SUPPORTED_PLAN_SECTIONS = {
    "PLAN-TASK-*", "Spec References", "Change Type", "TDD",
    "Verification", "Execution Sequencing", "Rollback / Safety Plan",
    "Stop / Escalation Conditions",
}


def _write_repair_request(
    output_path: Path,
    plan_path: Path,
    issues: list[str],
    required_action: str,
) -> None:
    repair_path = output_path.with_name(output_path.name + ".repair.md")
    repair_path.parent.mkdir(parents=True, exist_ok=True)
    issue_lines = "\n".join(f"- {issue}" for issue in issues)
    repair_path.write_text(
        f"# Post-PLAN Gap Repair Request\n\n"
        f"Adapter: {ADAPTER_NAME} {ADAPTER_RULE_VERSION}\n"
        f"Source: {plan_path}\n\n"
        f"## Issues\n\n"
        f"{issue_lines}\n\n"
        f"## Required Action\n\n"
        f"{required_action}\n",
        encoding="utf-8",
    )


def adapt_plan(plan_path: Path, output_path: Path) -> str:
    """Adapt neutral 07-plan.md to Superpowers-executable plan."""
    if not plan_path.exists():
        return "stale_source_detected"

    content = plan_path.read_text(encoding="utf-8")

    if not content.strip():
        return "stale_source_detected"

    # Extract plan title/work_id
    title_match = re.search(r'^# Plan:\s*(.+)$', content, re.MULTILINE)
    work_id = title_match.group(1).strip() if title_match else "unknown"

    # Parse PLAN-TASK sections
    task_sections = re.findall(
        r'^## (PLAN-TASK-\d+)\n(.*?)(?=^## |\Z)',
        content,
        re.MULTILINE | re.DOTALL,
    )

    if not task_sections:
        _write_repair_request(
            output_path,
            plan_path,
            [
                "No `PLAN-TASK-*` sections found in source plan.",
                "The source plan must have at least one `## PLAN-TASK-NNN` section.",
            ],
            "Add `## PLAN-TASK-NNN` sections to the source plan and re-run adaptation.",
        )
        return "adapter_gap_detected"

    missing_spec_refs = [
        task_id
        for task_id, task_body in task_sections
        if not re.search(r'^Spec References?:\s*(.+)$', task_body, re.MULTILINE)
    ]
    if missing_spec_refs:
        _write_repair_request(
            output_path,
            plan_path,
            [
                f"{task_id} is missing required `Spec References`."
                for task_id in missing_spec_refs
            ],
            "Add `Spec References: SPEC-...` to every `PLAN-TASK-*` section and re-run adaptation.",
        )
        return "adapter_gap_detected"

    # Build Superpowers plan
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Superpowers Plan: {work_id}",
        f"> Generated by Superpowers adapter {ADAPTER_RULE_VERSION} from {plan_path.name}",
        "",
    ]

    for task_id, task_body in task_sections:
        # Extract goal
        goal_match = re.search(r'^Goal:\s*(.+)$', task_body, re.MULTILINE)
        goal = goal_match.group(1).strip() if goal_match else task_id

        lines.append(f"## Task: {goal}")
        lines.append("")

        # Spec references
        spec_match = re.search(r'^Spec References?:\s*(.+)$', task_body, re.MULTILINE)
        if spec_match:
            lines.append("### Context")
            lines.append(f"Spec References: {spec_match.group(1).strip()}")
            lines.append("")

        # Steps
        steps_match = re.search(r'^Steps?:\n((?:\d+\..+\n?)+)', task_body, re.MULTILINE)
        if steps_match:
            lines.append("### Steps")
            lines.append(steps_match.group(0).rstrip())
            lines.append("")

        # TDD
        tdd_match = re.search(r'^TDD:\n((?:- .+\n?)+)', task_body, re.MULTILINE)
        if tdd_match:
            lines.append("### TDD")
            lines.append(tdd_match.group(0).rstrip())
            lines.append("")

        # Verification
        verif_match = re.search(r'^Verification:\n((?:- .+\n?)+)', task_body, re.MULTILINE)
        if verif_match:
            lines.append("### Verification")
            lines.append(verif_match.group(0).rstrip())
            lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return "derived_plan_written"
